name: Bug Report
description: Report a problem or unexpected behavior
title: "[BUG] - Short description of the bug"
labels: [bug]
assignees:
  - your-github-username

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I am experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug? Please be very specific.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: input
    id: browser-version
    attributes:
      label: Browser version
      description: Version of your browser

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other

  - type: input
    id: os-version
    attributes:
      label: OS version
      description: Version of your operating system.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
