export const PASSWORD_MANAGEMENT_SERVICE = 'PASSWORD_MANAGEMENT_SERVICE';

export const PASSWORD_HISTORY_REPOSITORY = 'PASSWORD_HISTORY_REPOSITORY';
export const PASSWORD_HISTORY_SERVICE = 'PASSWORD_HISTORY_SERVICE';
export const PASSWORD_HISTORY_MAX_COUNT = 3;

export const RESET_TOKEN_REPOSITORY = 'RESET_TOKEN_REPOSITORY';
export const RESET_TOKEN_SERVICE = 'RESET_TOKEN_SERVICE';
